version: '3.2'
services:
  api:
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - postgres
    volumes:
      - './:/usr/src/app'
    command: 'npm start'
  postgres:
    image: postgres:alpine
    restart: always
    expose:
      - 5432
    ports:
      - '5432:5432'
